// <auto-generated />
using System;
using API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20231231132405_orders")]
    partial class orders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShopOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopOrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfRatings")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4m,
                            ImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTp2qPay-quantum-smartphone.png",
                            IsFeatured = true,
                            LongDescription = "The Quantum X Smartphone isn't just a step ahead in mobile technology; it's a leap into the future. Integrated with groundbreaking quantum computing capabilities, this phone offers unparalleled processing speeds, making every task from web browsing to complex computations startlingly fast. The quantum processor is not only efficient but also significantly enhances the device's security, leveraging quantum encryption to protect your data like never before. The sleek, ultramodern design is complemented by an advanced AI assistant that learns and adapts to your preferences, ensuring a personalized experience. With an extended battery life that defies expectations and a camera system utilizing quantum algorithms for perfect shots, the Quantum X Smartphone redefines the boundaries of what a smartphone can do.",
                            Name = "Quantum X Smartphone",
                            NumberOfRatings = 1,
                            Price = 799.99m,
                            ProductCategoryId = 2,
                            ShortDescription = "Experience the power of quantum computing in your pocket!",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 5m,
                            ImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTgfbD9J-retro-flip-phone.png",
                            IsFeatured = true,
                            LongDescription = "The Retro Flip Phone combines the nostalgic charm of the classic flip phone design with the cutting-edge technology of today. This device is a stylish nod to the past, featuring a tactile flipping mechanism that is satisfying to use. The exterior displays a sleek, retro-inspired look, while the interior boasts a modern touchscreen interface alongside traditional keypad options. The Retro Flip Phone caters to those who seek simplicity without sacrificing modern functionalities such as high-quality cameras, fast 4G LTE connectivity, and access to all your favorite apps. It's the perfect blend of old-school cool and contemporary tech, designed for users who appreciate simplicity and style.",
                            Name = "Retro Flip Phone",
                            NumberOfRatings = 1,
                            Price = 299.99m,
                            ProductCategoryId = 2,
                            ShortDescription = "A blast from the past with modern features and a flip design!",
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 0m,
                            ImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTn6fy2p-fusionbook-pro.png",
                            IsFeatured = true,
                            LongDescription = "The FusionBook Pro is the ultimate laptop for those who demand versatility without compromise. It expertly blends powerful performance with an elegant design, making it ideal for both professional and personal use. The laptop features a high-performance processor and advanced graphics card, handling demanding software applications and high-end gaming with ease. Its innovative design includes a high-resolution, edge-to-edge display that offers stunning visuals, whether you're working on a presentation or watching your favorite movie. The FusionBook Pro also includes enhanced audio capabilities for an immersive experience and a battery that lasts all day, ensuring that work and play can continue uninterrupted.",
                            Name = "FusionBook Pro",
                            NumberOfRatings = 0,
                            Price = 1499.99m,
                            ProductCategoryId = 3,
                            ShortDescription = "The laptop that fuses work and play seamlessly.",
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4m,
                            ImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTm1zM9j-stealth-ninja-laptop.png",
                            IsFeatured = true,
                            LongDescription = "The Stealth Ninja Laptop is the epitome of discretion and performance. Designed specifically for users who require both privacy and speed, this laptop features a unique, ultra-quiet keyboard that allows for silent typing, perfect for working in quiet environments or during covert operations. Its matte black finish and compact design make it inconspicuous and easy to carry. Underneath its stealthy exterior lies a powerful processor and ample memory, providing lightning-fast speeds and seamless multitasking capabilities. Enhanced security features, including biometric authentication and robust encryption, protect sensitive information, making the Stealth Ninja Laptop a top choice for professionals in security-sensitive fields.",
                            Name = "Stealth Ninja Laptop",
                            NumberOfRatings = 1,
                            Price = 1999.99m,
                            ProductCategoryId = 3,
                            ShortDescription = "Designed for covert operations with silent keystrokes and ninja speed.",
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 0m,
                            ImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTjZbRGL-zephyr-earbuds.png",
                            IsFeatured = false,
                            LongDescription = "The Zephyr Wireless Earbuds redefine the listening experience with their feather-light design and exceptional sound quality. These earbuds are so light and comfortable that you might forget you're wearing them, but their sound performance will quickly remind you. They offer crystal-clear audio with deep bass and rich treble, immersing you in your music like never before. The earbuds feature cutting-edge wireless technology, ensuring a stable connection without the hassle of cords. With an intuitive touch interface, you can control your music, take calls, and access your voice assistant with ease. The Zephyr Wireless Earbuds also boast a long-lasting battery life, and their sleek, ergonomic design ensures they stay securely in place, whether you're relaxing at home or on the move.",
                            Name = "Zephyr Wireless Earbuds",
                            NumberOfRatings = 0,
                            Price = 89.99m,
                            ProductCategoryId = 5,
                            ShortDescription = "Earbuds so light they might just make you float!",
                            Stock = 200
                        });
                });

            modelBuilder.Entity("API.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptops",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Desktops",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("API.Models.ShopOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShopOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2023, 12, 13, 15, 24, 5, 219, DateTimeKind.Local).AddTicks(5181),
                            Status = "Delivered",
                            TotalPrice = 799.99m,
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2023, 12, 12, 15, 24, 5, 219, DateTimeKind.Local).AddTicks(5306),
                            Status = "Delivered",
                            TotalPrice = 299.99m,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2023, 12, 21, 15, 24, 5, 219, DateTimeKind.Local).AddTicks(5311),
                            Status = "Delivered",
                            TotalPrice = 1999.99m,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageURL")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ada@example.com",
                            FirstName = "Ada",
                            LastName = "Lovelace",
                            PasswordHash = "$2a$13$ymTlzWaScHKmTAk5IDPNKumnTglmOIi7vJUNhf/vpP/6Gp3tWRf6S",
                            PhoneNumber = "888888888",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvUBANt6N-ada-lovelace-coding.png",
                            Type = 999,
                            Username = "AdaCoder"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alan@example.com",
                            FirstName = "Alan",
                            LastName = "Turing",
                            PasswordHash = "$2a$13$/0YwBXyX35QHUm4tP.7hW.Lli.N/R1XFsZybVLmqqmAY0EjmpLnLO",
                            PhoneNumber = "999999999",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvU3Sp34D-alan-turing-doing-math.png",
                            Type = 999,
                            Username = "AnalyticalAlan"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charles@example.com",
                            FirstName = "Charles",
                            LastName = "Babbage",
                            PasswordHash = "$2a$13$jjw.8hqysioNWfGZegmbz.ZMz6GcwDUYSnod1H9sSc/mDg36l9aQu",
                            PhoneNumber = "777777777",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTzyWF9X-charles-babbage%20building-analytical-engine.png",
                            Type = 999,
                            Username = "BabbageEngineer"
                        },
                        new
                        {
                            Id = 4,
                            Email = "worker1@example.com",
                            FirstName = "Worker1",
                            LastName = "LastName1",
                            PasswordHash = "$2a$13$FziTzqz06qVZ9NEZDu8Jkuryn4nlrTG8y5AUabI8IMonMpCRnA/Mq",
                            PhoneNumber = "98765431",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTy4qQ8x-865056_electronic%20store%20worker%20_xl-1024-v1-0.png",
                            Type = 1,
                            Username = "worker1"
                        },
                        new
                        {
                            Id = 5,
                            Email = "worker2@example.com",
                            FirstName = "Worker2",
                            LastName = "LastName2",
                            PasswordHash = "$2a$13$v7kdMGmyquOaTLDEOJJ8fOSq5USCM2OU0fNA/GNHuzLi0AY7idJvC",
                            PhoneNumber = "98765432",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTy4qQ8x-865056_electronic%20store%20worker%20_xl-1024-v1-0.png",
                            Type = 1,
                            Username = "worker2"
                        },
                        new
                        {
                            Id = 6,
                            Email = "worker3@example.com",
                            FirstName = "Worker3",
                            LastName = "LastName3",
                            PasswordHash = "$2a$13$tvrw7cM.FcVmLC6hYfqlue1qAzBJu1V9B7ltmc3wbsgekI3Hbm3Au",
                            PhoneNumber = "98765433",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTy4qQ8x-865056_electronic%20store%20worker%20_xl-1024-v1-0.png",
                            Type = 1,
                            Username = "worker3"
                        },
                        new
                        {
                            Id = 7,
                            Email = "customer1@example.com",
                            FirstName = "Customer1",
                            LastName = "LastName1",
                            PasswordHash = "$2a$13$ocYeOxt6YqArURBbKR12/uuN3KXok3WaPMO3HIz0NygUi8oOYNAQK",
                            PhoneNumber = "12345671",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTtNgM2b-773905_guy%20with%20sunglasses%20_xl-1024-v1-0.png",
                            Type = 0,
                            Username = "customer1"
                        },
                        new
                        {
                            Id = 8,
                            Email = "customer2@example.com",
                            FirstName = "Customer2",
                            LastName = "LastName2",
                            PasswordHash = "$2a$13$6cKP25M0fAuwHIVvVjnQ4OYf6mgfCfdE.3Rl/zWo.hXC9xJP2jMF.",
                            PhoneNumber = "12345672",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTtNgM2b-773905_guy%20with%20sunglasses%20_xl-1024-v1-0.png",
                            Type = 0,
                            Username = "customer2"
                        },
                        new
                        {
                            Id = 9,
                            Email = "customer3@example.com",
                            FirstName = "Customer3",
                            LastName = "LastName3",
                            PasswordHash = "$2a$13$1URKnaPKpGrW6NFaG7iUAuCilh6Hi36vwdAVbHlcZAuHQ7FA8kt.q",
                            PhoneNumber = "12345673",
                            ProfileImageURL = "https://upcdn.io/W142iFr/raw/uploads/2023/12/31/4kvTtNgM2b-773905_guy%20with%20sunglasses%20_xl-1024-v1-0.png",
                            Type = 0,
                            Username = "customer3"
                        });
                });

            modelBuilder.Entity("API.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "123 Computing Street",
                            City = "London",
                            Country = 826,
                            PostalCode = "SW1A 1AA",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "456 Code Avenue",
                            City = "Cambridge",
                            Country = 826,
                            PostalCode = "CB2 1TN",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "789 Analytical Drive",
                            City = "London",
                            Country = 826,
                            PostalCode = "WC2B 6JR",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "321 Rue de Paris",
                            City = "Paris",
                            Country = 250,
                            PostalCode = "75001",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "123 Hauptstraße",
                            City = "Berlin",
                            Country = 276,
                            PostalCode = "10115",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "789 Tech Street",
                            City = "New York",
                            Country = 840,
                            PostalCode = "10001",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "456 Sydney Road",
                            City = "Sydney",
                            Country = 36,
                            PostalCode = "2000",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            AddressLine = "987 Maple Lane",
                            City = "Toronto",
                            Country = 124,
                            PostalCode = "M5J 2N8",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            AddressLine = "654 Britannia Street",
                            City = "London",
                            Country = 826,
                            PostalCode = "WC1X 9JP",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("API.Models.UserReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "The Quantum X Smartphone is impressive, especially the quantum computing capabilities!",
                            ProductId = 1,
                            Rating = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            Comment = "I love the Retro Flip Phone. It combines nostalgia with modern features!",
                            ProductId = 2,
                            Rating = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            Comment = "The Stealth Ninja Laptop lives up to its name. It's fast and silent!",
                            ProductId = 4,
                            Rating = 4,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("API.Models.OrderLine", b =>
                {
                    b.HasOne("API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.ShopOrder", null)
                        .WithMany("OrderLines")
                        .HasForeignKey("ShopOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasOne("API.Models.ProductCategory", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.ProductCategory", b =>
                {
                    b.HasOne("API.Models.ProductCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("API.Models.ShopOrder", b =>
                {
                    b.HasOne("API.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.UserAddress", b =>
                {
                    b.HasOne("API.Models.User", null)
                        .WithOne("Address")
                        .HasForeignKey("API.Models.UserAddress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.UserReview", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("API.Models.ShopOrder", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
